apiVersion: v1
kind: Namespace
metadata:
  name: last9
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: last9
type: Opaque
stringData:
  aws-credentials: |
    [k8streamer]
    aws_access_key_id=1
    aws_secret_access_key=2
    region=<region of the s3 bucket, ex- ap-south-1>
    output=json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8stream-config
  namespace: last9
data:
  config.json: |
    {
      "config": {
            "uid": "<uuid>",
            "heartbeat_hook": "https://heartbeat.last9.io",
            "heartbeat_interval": 60,
            "batch_interval": 30,
            "batch_size": 10000,
            "sink": "s3"
        },
        "prefix": "<prefix>",
        "aws_bucket": "<s3-bucket>",
        "aws_profile": "k8streamer",
        "aws_region": "<region of the bucket, ex: ap-south-1>",
        "kubeconfig": ""
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: last9
  name: k8stream
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8stream
# These rules will be added to the "monitoring" role.
rules:
- apiGroups: ["*"]
  resources: ["services", "endpoints", "pods", "nodes", "events", "deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8stream
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8stream
subjects:
  - kind: ServiceAccount
    namespace: last9
    name: k8stream
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8stream
  namespace: last9
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8stream
      annotations:
        version: latest
    spec:
      serviceAccountName: k8stream
      restartPolicy: Always
      containers:
        - name: k8stream
          imagePullPolicy: Always
          image: last9inc/k8stream:latest
          env:
            - name: VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['version']
          volumeMounts:
            - mountPath: /data
              name: cfg

            - name: credentials
              mountPath: /root/.aws
      volumes:
        - name: cfg
          configMap:
            name: k8stream-config

        - name: credentials
          secret:
            secretName: credentials
            items:
              - key: aws-credentials
                path: credentials
  selector:
    matchLabels:
      app: k8stream
